"""add_analysis_columns_to_reports

Revision ID: 1f0105e742c5
Revises: f3d8a1c6e902
Create Date: 2026-03-15 13:21:22.708583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f0105e742c5'
down_revision: Union[str, None] = 'f3d8a1c6e902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('target_schema_version', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aj_job_type', 'analysis_jobs', ['job_type'], unique=False)
    op.create_index('idx_aj_report_id', 'analysis_jobs', ['report_id'], unique=False)
    op.create_index('idx_aj_status', 'analysis_jobs', ['status'], unique=False)
    op.create_table('report_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('report_category', sa.String(length=20), nullable=False),
    sa.Column('analysis_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('llm_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('extraction_quality', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index('idx_report_analysis_category', 'report_analysis', ['report_category'], unique=False)
    op.create_index('idx_report_analysis_schema_ver', 'report_analysis', ['schema_version'], unique=False)
    op.create_table('report_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('keyword_type', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rk_keyword', 'report_keywords', ['keyword'], unique=False)
    op.create_index('idx_rk_keyword_type', 'report_keywords', ['keyword_type'], unique=False)
    op.create_index('idx_rk_report_id', 'report_keywords', ['report_id'], unique=False)
    op.create_index('uq_report_keyword', 'report_keywords', ['report_id', 'keyword'], unique=True)
    op.create_table('report_markdown',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('markdown_text', sa.Text(), nullable=False),
    sa.Column('converter', sa.String(length=50), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_table('report_sector_mentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('mention_type', sa.String(length=20), nullable=False),
    sa.Column('impact', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rscm_report_id', 'report_sector_mentions', ['report_id'], unique=False)
    op.create_index('idx_rscm_sector', 'report_sector_mentions', ['sector'], unique=False)
    op.create_index('uq_report_sector', 'report_sector_mentions', ['report_id', 'sector'], unique=True)
    op.create_table('report_stock_mentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('mention_type', sa.String(length=20), nullable=False),
    sa.Column('impact', sa.String(length=20), nullable=True),
    sa.Column('relevance_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rsm_mention_type', 'report_stock_mentions', ['mention_type'], unique=False)
    op.create_index('idx_rsm_report_id', 'report_stock_mentions', ['report_id'], unique=False)
    op.create_index('idx_rsm_stock_code', 'report_stock_mentions', ['stock_code'], unique=False)
    op.create_index('uq_report_stock', 'report_stock_mentions', ['report_id', 'stock_code'], unique=True)
    op.add_column('reports', sa.Column('analysis_status', sa.String(length=20), nullable=True))
    op.add_column('reports', sa.Column('analysis_version', sa.String(length=20), nullable=True))
    op.add_column('reports', sa.Column('markdown_converted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_index('ix_reports_parse_quality', table_name='reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_report_dedup', 'reports', ['broker', 'report_date', 'analyst', 'stock_name', 'title_normalized'], postgresql_nulls_not_distinct=True)
    op.create_index('ix_reports_parse_quality', 'reports', ['parse_quality'], unique=False)
    op.drop_column('reports', 'markdown_converted')
    op.drop_column('reports', 'analysis_version')
    op.drop_column('reports', 'analysis_status')
    op.drop_index('uq_report_stock', table_name='report_stock_mentions')
    op.drop_index('idx_rsm_stock_code', table_name='report_stock_mentions')
    op.drop_index('idx_rsm_report_id', table_name='report_stock_mentions')
    op.drop_index('idx_rsm_mention_type', table_name='report_stock_mentions')
    op.drop_table('report_stock_mentions')
    op.drop_index('uq_report_sector', table_name='report_sector_mentions')
    op.drop_index('idx_rscm_sector', table_name='report_sector_mentions')
    op.drop_index('idx_rscm_report_id', table_name='report_sector_mentions')
    op.drop_table('report_sector_mentions')
    op.drop_table('report_markdown')
    op.drop_index('uq_report_keyword', table_name='report_keywords')
    op.drop_index('idx_rk_report_id', table_name='report_keywords')
    op.drop_index('idx_rk_keyword_type', table_name='report_keywords')
    op.drop_index('idx_rk_keyword', table_name='report_keywords')
    op.drop_table('report_keywords')
    op.drop_index('idx_report_analysis_schema_ver', table_name='report_analysis')
    op.drop_index('idx_report_analysis_category', table_name='report_analysis')
    op.drop_table('report_analysis')
    op.drop_index('idx_aj_status', table_name='analysis_jobs')
    op.drop_index('idx_aj_report_id', table_name='analysis_jobs')
    op.drop_index('idx_aj_job_type', table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
