"""initial

Revision ID: 425dd3c249af
Revises: 
Create Date: 2026-03-08 13:36:13.132685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '425dd3c249af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_message_id', sa.BigInteger(), nullable=True),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_username')
    )
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('analyst', sa.String(length=100), nullable=True),
    sa.Column('stock_name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_normalized', sa.String(length=500), nullable=True),
    sa.Column('stock_code', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=True),
    sa.Column('opinion', sa.String(length=30), nullable=True),
    sa.Column('target_price', sa.Integer(), nullable=True),
    sa.Column('prev_opinion', sa.String(length=30), nullable=True),
    sa.Column('prev_target_price', sa.Integer(), nullable=True),
    sa.Column('earnings_quarter', sa.String(length=10), nullable=True),
    sa.Column('est_revenue', sa.BigInteger(), nullable=True),
    sa.Column('est_op_profit', sa.BigInteger(), nullable=True),
    sa.Column('est_eps', sa.Integer(), nullable=True),
    sa.Column('earnings_surprise', sa.String(length=20), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('pdf_size_kb', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.SmallInteger(), nullable=True),
    sa.Column('pdf_download_failed', sa.Boolean(), nullable=False),
    sa.Column('source_channel', sa.String(length=100), nullable=False),
    sa.Column('source_message_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_sentiment', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('ai_keywords', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('ai_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_analyst', 'reports', ['analyst', 'report_date'], unique=False)
    op.create_index('ix_reports_broker', 'reports', ['broker', 'report_date'], unique=False)
    op.create_index('ix_reports_date', 'reports', ['report_date'], unique=False)
    op.create_index('ix_reports_pdf_failed', 'reports', ['pdf_download_failed'], unique=False)
    op.create_index('ix_reports_sector', 'reports', ['sector', 'report_date'], unique=False)
    op.create_index('ix_reports_source', 'reports', ['source_channel', 'collected_at'], unique=False)
    op.create_index('ix_reports_stock', 'reports', ['stock_name', 'report_date'], unique=False)
    op.create_index('ix_reports_stock_code', 'reports', ['stock_code', 'report_date'], unique=False)
    op.create_index('ix_reports_type', 'reports', ['report_type', 'report_date'], unique=False)
    op.create_table('stock_codes',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_normalized', sa.String(length=100), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('ix_stock_codes_name', 'stock_codes', ['name'], unique=False)
    # ### end Alembic commands ###

    # 중복 제거용 unique constraint (NULLS NOT DISTINCT - PostgreSQL 15+)
    op.execute("""
        ALTER TABLE reports ADD CONSTRAINT uix_report_dedup
        UNIQUE NULLS NOT DISTINCT (broker, report_date, analyst, stock_name, title_normalized)
    """)

    # updated_at 자동 갱신 트리거
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER trg_reports_updated_at
        BEFORE UPDATE ON reports
        FOR EACH ROW EXECUTE FUNCTION update_updated_at()
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_reports_updated_at ON reports")
    op.execute("DROP FUNCTION IF EXISTS update_updated_at")
    op.execute("ALTER TABLE reports DROP CONSTRAINT IF EXISTS uix_report_dedup")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_codes_name', table_name='stock_codes')
    op.drop_table('stock_codes')
    op.drop_index('ix_reports_type', table_name='reports')
    op.drop_index('ix_reports_stock_code', table_name='reports')
    op.drop_index('ix_reports_stock', table_name='reports')
    op.drop_index('ix_reports_source', table_name='reports')
    op.drop_index('ix_reports_sector', table_name='reports')
    op.drop_index('ix_reports_pdf_failed', table_name='reports')
    op.drop_index('ix_reports_date', table_name='reports')
    op.drop_index('ix_reports_broker', table_name='reports')
    op.drop_index('ix_reports_analyst', table_name='reports')
    op.drop_table('reports')
    op.drop_table('channels')
    # ### end Alembic commands ###
