"""add_trade_tables

Revision ID: f6e228957724
Revises: d4b7f2e9a316
Create Date: 2026-03-21 10:02:23.403916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6e228957724'
down_revision: Union[str, None] = 'd4b7f2e9a316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('traded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('broker', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'traded_at', 'side', 'price', 'quantity', 'broker', name='uq_trade_dedup')
    )
    op.create_index('ix_trades_side', 'trades', ['side'], unique=False)
    op.create_index('ix_trades_symbol', 'trades', ['symbol'], unique=False)
    op.create_index('ix_trades_traded_at', 'trades', ['traded_at'], unique=False)
    op.create_table('trade_indicators',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=False),
    sa.Column('stoch_k_d', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rsi_14', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('macd', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ma_position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bb_position', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('snapshot_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    op.create_table('trade_pairs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('buy_trade_id', sa.BigInteger(), nullable=False),
    sa.Column('sell_trade_id', sa.BigInteger(), nullable=False),
    sa.Column('profit_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buy_trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sell_trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_pairs_buy_trade_id', 'trade_pairs', ['buy_trade_id'], unique=False)
    op.create_index('ix_trade_pairs_sell_trade_id', 'trade_pairs', ['sell_trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_pairs_sell_trade_id', table_name='trade_pairs')
    op.drop_index('ix_trade_pairs_buy_trade_id', table_name='trade_pairs')
    op.drop_table('trade_pairs')
    op.drop_table('trade_indicators')
    op.drop_index('ix_trades_traded_at', table_name='trades')
    op.drop_index('ix_trades_symbol', table_name='trades')
    op.drop_index('ix_trades_side', table_name='trades')
    op.drop_table('trades')
    # ### end Alembic commands ###
